global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - \"first_rules.yml\"
  # - \"second_rules.yml\"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s
    metrics_path: /metrics

  # Vehicle Manager application metrics (via OTEL Collector)
  - job_name: 'vehicle-manager'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s
    metrics_path: /metrics

  # Direct scraping from vehicle manager if it exposes metrics endpoint
  - job_name: 'vehicle-manager-direct'
    static_configs:
      - targets: ['vehicle-manager:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s